FROM ubuntu:latest
MAINTAINER Hanantadk "hanantadk@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /project/main
WORKDIR /project/main
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["main.py"]